---
sidebar: sidebar
permalink: alm-applications.html
summary: An explanation of NKS ALM Applications and how to use them.
---

= ALM Applications

Wondering what an ALM Application is and how to use it? Get an overview of the Application deployment workflow, and how you can use `git push` to deploy and manage Application with https://nks.netapp.io[NetApp Kubernetes Service (NKS)] Application Lifecycle Management.

NOTE: Applications are currently in Functional Preview mode. To enable this feature you will need to create a new cluster. Be sure to enable experimental features in step 2 of the cluster creation process.

For more information on Kubernetes deployments, https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[see the official Kubernetes documentation].

== Understanding Applications

By creating and leveraging Applications, you can quickly build and deploy solutions to your NKS cluster.

After creating an Application, NKS will provide you with a `git remote` command you can use to deploy your code. NKS also provides the URL (ingress) for accessing the code after it has been deployed.

Developers can `git push` code to NKS, and NKS takes it from there. NKS will automatically build the container and deploy your code to the cluster. The Application is deployed to the cluster namespace which matches the project name.

== Supported Languages

The following languages are supported by Applications and the `git push` workflow:

- Clojure
- Go
- Gradle
- Java
- Node
- PHP
- Play
- Python
- Ruby
- Scala
- HTML

NOTE: To serve static HTML pages, be sure to add an empty file named `.static` in the root directory.

== Using Applications

Prerequisites:

* Before deploying your Application on NKS, you will need to commit it to a Git repository. You can either use a local repository on your desktop computer, or use a public https://github.com[GitHub] repository.
* https://git-scm.com/[Git] installed on your desktop computer.

=== Create an Application

1. Go to App Management https://nks.netapp.io/v2
2. Select a workspace
3. Press the Projects tab
4. Select a project
5. At the bottom of the page, press the [Add Solution] button
6. Press Application
7. Enter a name for identifying your application.
8. Select an update strategy - this maps to the deployment object in Kubernetes.
9. Optionally, enable autoscaling of the application by setting minimum and maximum replicas and CPU trigger values.


=== Deploy to cluster

1. Copy the `git remote` address from the Project page
2. On your terminal, paste the `git remote` address.
3. Commit your changes
4. `git push nks master`

And that’s it - `kubectl get pods -n project_name -w` to see the pods come up.

=== Access the application

From the application detail page, press the link or copy the link.
