---
sidebar: sidebar
permalink: alm-quickstart.html
summary: Quickstart guide for NKS ALM
---

= ALM Quickstart Guide

Learn how to get up and running with https://nks.netapp.io[NetApp Kubernetes Service (NKS)] Application Lifecycle Management.

== Overview

Application Lifecycle Management (ALM) provides a developer-friendly `git push` workflow which lets you deploy your application to an NKS Kubernetes cluster with a simple `git push nks master`. Apps can be deployed with monitoring and more.

== Applications

By creating and leveraging Applications, you can quickly build and deploy solutions to your NKS cluster.

After creating an Application, NKS will provide you with a `git remote` command you can use to deploy your code. NKS also provides the URL (ingress) for accessing the code after it has been deployed.

Developers can `git push` code to NKS, and NKS takes it from there. NKS will automatically build the container and deploy your code to the cluster. The Application is deployed to the cluster namespace which matches the project name.

Learn more in our https://docs.netapp.com/us-en/kubernetes-service/alm-applications.html[ALM Applications Guide].

== Trackers

Trackers provide a method to visualize the state of Kubernetes objects that were created by directly applying manifests. This is accomplished by tracking Kubernetes labels and presenting that information in the NKS UI.

For more information about Trackers, see our https://docs.netapp.com/us-en/kubernetes-service/alm-trackers.html[ALM Trackers Guide].

== Packages

For more information about Packages, see our https://docs.netapp.com/us-en/kubernetes-service/alm-packages.html[ALM Packages Guide].
