---
sidebar: sidebar
permalink: alm-applications.html
summary: An explanation of NKS ALM Applications and how to use them.
---

= ALM Applications

By using Applications, users enable a git-push workflow to deploy and manage applications.

== Prerequisites

Applications are part of the Application Lifecycle Management (ALM) suite currently in functional preview mode. To access this feature, you must enable experimental features in Step 2 of the Create Cluster wizard.

== Understanding Applications

By creating and leveraging Applications, you can quickly build and deploy solutions to your NKS cluster.

After creating an Application, you are provided a `git remote` address for deploying your code and the URL, or ingress, used for accessing the code pushed to NKS.

Developers can `git push` code and NKS automatically builds the container and deploys it your cluster. The application is deployed to the cluster namespace matching the project name.

== Supported Languages

The following languages are supported by Applications and the git-push workflow

- Clojure
- Go
- Gradle
- Java
- Node
- PHP
- Play
- Python
- Ruby
- Scala
- HTML*

NOTE: for static pages, please add an empty file named `.static` in the root directory.

== Using Applications
=== Create an Application

1. Go to App Management https://nks.netapp.io/v2
2. Select a workspace
3. Press the Projects tab
4. Select a project
5. At the bottom of the page, press the [Add Solution] button
6. Press Application
7. Enter a name for identifying your application.
8. Select an update strategy - this maps to the deployment object in Kubernetes.
9. Optionally, enable autoscaling of the application by setting minimum and maximum replicas and CPU trigger values.

=== Deploy to cluster

1. Copy the `git remote` address from the Project page
1. On your terminal, paste the `git remote` address.
1. Commit your changes
1. `git push nks master`

And that’s it - `kubectl get pods -n project_name -w` to see the pods come up.

=== Access the application

From the application detail page, press the link or copy the link.

=== More Information

Kubernetes Deployments
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
