---
sidebar: sidebar
permalink: eol.html
summary: More information on the StackPoint.io sunset.
---

= StackPoint.io Sunset Notification

Stackpoint.io is now http://nks.netapp.io[NetApp Kubernetes Service (NKS)]. Stackpoint.io users are **unable to create new clusters** and **cannot sign up or renew subscriptions.** All users are encouraged to make an account on nks.netapp.io today.

This transitional period will last until June 17. After June 17, **users will not be able to log in to the site.** Any active clusters will be left running at the provider site. We have judged this to be the least disruptive way to handle the transition.

Be sure to migrate any active clusters to http://nks.netapp.io[NetApp Kubernetes Service (NKS)] before that date. If you prefer not to migrate to NKS, we strongly recommend you download your cluster's kubeconfig file and SSH keys before the June 17 shutdown.

== Migration Suggestions and Tips

**Volumes**

If you have volumes, please follow these instructions:

* Detach the volumes from the current nodes.
* Manually add the existing volumes to the new K8s cluster. More information on this process can be found in the official Kubernetes documentation.
* Modify your pods to consume the volumes.

NOTE: If you have a volume type hostpath in use, that data should be manually migrated to the new cluster.

**Load Balancer Services**

* Determine which services at your cluster are using cloud provider load balancers.
* Find the CNAMEs you set up at your DNS for those services.
* Create the same services at the new cluster. This will create a new set of load balancers.
* After the entire load is running at the new cluster, modify your CNAME entries to point to the new load balancers.

**Ingress**

* Determine the IP that the ingress is exposing. This is the node’s IP address.
* Find the CNAMEs you set up for that IP address.
* Create the ingress at the new cluster, and retrieve the node’s new IP address.
* After the entire load is running at the new cluster, modify your CNAME entries to point to the new IP address.
