---
sidebar: sidebar
permalink: getting-started-add-credentials.html
summary: Intro to adding provider credentials to NKS
---

= Getting Started: Add Provider Credentials

The next step is to locate your provider credentials and add them to your organization. When you add your provider credentials, you have the option to assign the credentials to a specific workspace and/or team.

== Provider Credential Security

Your provider credentials are added to NKS as a keypair or token. This provides an extra layer of security and access control. Your members can use the credentials without needing to have the actual provider login information.

Any member who has access to a set of provider credentials will be able to add, delete, scale, and otherwise manage clusters on that provider account. However, they will not be able to use those credentials to log in to the provider's site directly.

Only members with the Admin role will be able to view, update, or delete the provider credentials in your NKS account.

== Add Provider Credentials

For step-by-step instructions on finding and adding your provider credentials, see our documentation for:

* https://docs.netapp.com/us-en/kubernetes-service/create-auth-credentials-on-aws.html[AWS]
* https://docs.netapp.com/us-en/kubernetes-service/find-aws-credentials-for-cvs.html[AWS for CVS]
* https://docs.netapp.com/us-en/kubernetes-service/create-auth-credentials-on-azure.html[Azure]
* https://docs.netapp.com/us-en/kubernetes-service/create-auth-credentials-on-gce.html[GCE]
* https://docs.netapp.com/us-en/kubernetes-service/create-auth-credentials-on-gke.html[GKE]
* https://docs.netapp.com/us-en/kubernetes-service/hci-enable-nks-for-netapp-hci.html[NetApp HCI]
* https://docs.netapp.com/us-en/kubernetes-service/register-vmware.html[VMware]
