---
sidebar: sidebar
permalink: getting-started-user-access.html
summary: User access introductory NKS training
---

= Getting Started: Controlling User Access with Workspaces and Teams

When you begin working with your new NKS account, this is a good time to give some thought to how you might want to restrict access.

NOTE: Although you need to create your business organization up front, you can add, manage, and remove workspaces and teams at any time.

=== Workspaces

Workspaces are the middle layer of user access. Each organization can have multiple workspaces. Each workspace can have multiple teams. However, each workspace can only belong to one organization, and each team can only belong to one workspace.

**Example**

Acme Industries is a global, multinational conglomerate with thousands of potential NKS users. To begin, you might create workspaces for the Sales, Development, and QA departments.

**Workspaces Checklist**

* Set up workspaces for the broadest user categories, if applicable.
* Don't worry, you can always add and manage workspaces later.

=== Teams

Teams are the most granular layer of user access. Each member can belong to multiple teams.

**Example**

For Acme Industries, you decide to create two teams assigned to the Sales department's workspace: one for the West Coast sales team, and one for the East Coast sales team. These teams have separate cost centers, so they want to keep their provider credentials separate. There's also some friction between the two teams, so you want to keep the peace by ensuring that they can't accidentally delete each other's clusters.

**Teams Checklist**

* Set up teams for fine-grained control of user groups.
* Don't worry, you can always add and manage workspaces later.
