---
sidebar: sidebar
permalink: migrate-a-cluster.html
summary: Learn how to use NKS storage
---

= Migrate a Cluster

To migrate to a new cluster, follow these instructions.

== Volumes

If you have volumes:

* Detach the volumes from the current nodes.
* Manually add the existing volumes to the new K8s cluster. More information on this process can be found in https://kubernetes.io/docs/concepts/storage/volumes/#aws-ebs-example-configuration[the official Kubernetes documentation].
* Modify your pods to consume the volumes.

NOTE: If you have a volume type hostpath in use, that data should be manually migrated to the new cluster.

== Load Balancer Services

* Determine which services at your cluster are using cloud provider load balancers.
* Find the CNAMEs you set up at your DNS for those services.
* Create the same services at the new cluster. This will create a new set of load balancers.
* After the entire load is running at the new cluster, modify your CNAME entries to point to the new load balancers.

== Ingress

* Determine the IP that the ingress is exposing. This is the node’s IP address.
* Find the CNAMEs you set up for that IP address.
* Create the ingress at the new cluster, and retrieve the node’s new IP address.
* After the entire load is running at the new cluster, modify your CNAME entries to point to the new IP address.
