---
sidebar: sidebar
permalink: netapp-hci-requirements.html
summary: Requirements for using NetApp HCI with NKS
---

= NetApp HCI Requirements

The following are requirements for using NetApp HCI with https://nks.netapp.io[NetApp Kubernetes Service (NKS)]. For more information about using NetApp HCI, see http://docs.netapp.com/hci/index.jsp[the official NetApp HCI documentation].

* A NetApp HCI system successfully installed. We do not currently support cloud services on non-HCI systems.
* System size requirements:
    - 2x4 systems are not supported for production use. However, you can use these for demo work.
    - 3x4 systems are the minimum production system size we support.
    - 4x4 systems are the recommended minimum size.
    - NetApp HCI v1.6 or later.
* Any version of vSphere supported by NetApp HCI.
* vSphere distributed switches (VDS). We do not support installing to standard switches.
* Management node 2.1 (requires updates from the 2.0 version).
* Optional: Networks for NKS (and other services) pre-created in vCenter.
* An https://nks.netapp.io[NKS] account.
* An NKS API token.
    - This token authorizes the installer to access your NKS Organization.
    - To create an NKS API token, log in to NKS and click your user icon in the upper right-hand corner. Click **Edit Profile** then **Add Token**.
    - You can create the token at any time, even if you have not yet enabled cloud services on NetApp HCI.

== More NetApp HCI Resources

If you have any of the following issues:

* Replica pods deployed on different worker nodes. Trident’s guardrails prohibit the PVC Access Mode RWX with an iSCSI driver.  In this case, no pods will come up.
* Kubernetes Rolling Updates unsuccessful when a persistent volume is attached to the pod with iSCSI.
* Ungraceful Kubernetes worker node loss due to multi-attach errors when RWO is configured.

https://kb.netapp.com/app/answers/answer_view/a_id/1091520[See this KB article for solutions.]
