---
sidebar: sidebar
permalink: news.html
summary: News and updates for NetApp Kubernetes Service (NKS)
---

= What's New

News and updates for NetApp Kubernetes Service (NKS).

== Any Cloud, One Experience – Managed Kubernetes on VMware

**Nov 26, 2019**

Kubernetes gives an enterprise a standardized way to run containerized workloads anywhere at scale and with resiliency. NetApp Kubernetes Services is a management platform which provides operators, developers, and others the ability to manage Cloud Native Applications and Kubernetes infrastructure anywhere it is placed without needing prior knowledge. https://blog.netapp.com/any-cloud-one-experience-managed-kubernetes-on-vmware/[Read more...]

== Introducing the NetApp Kubernetes Services Terraform Provider

**March 6, 2019**

Terraform gives us a predictable method to build, update, and version our infrastructure. It has become an essential tool at many enterprises that use NKS.

We’re excited to announce that, in the 1.0.0 release of the NetApp Kubernetes Services Terraform Provider, you can automate management of your multi-cloud Kubernetes infrastructure and the workload running on it. This can be done on a single cluster or many clusters — across one or many cloud providers. https://blog.stackpoint.io/introducing-the-netapp-kubernetes-services-terraform-provider-df60eba53d5a[Read more...]

== Stackpoint.io Joins the NetApp Family

**Nov 17, 2018**

Seattle and New York — September 17, 2018 — We’re excited to announce we are joining the NetApp family. After numerous conversations where time was forgotten and we got lost in ideas, we realized NetApp’s and Stackpoint’s vision for Cloud Native workload and infrastructure management aligned. https://blog.stackpoint.io/stackpoint-io-joins-the-netapp-family-d0712ad54e81[Click here to read more.]
