---
sidebar: sidebar
permalink: teams-intro.html
summary: Learn how to use NKS Teams
---

= Teams

You can use teams, in conjunction with workspaces, to organize users and restrict their access on your https://nks.netapp.io[NetApp Kubernetes Service (NKS)] account.

* Each team can have many members.
* Each workspace can be assigned to many teams.
* Provider credentials can be restricted to specific workspaces.

As an example, let's say you have:

* One group of users who are developing applications for AWS and thus only need access to your AWS credentials.
* Another group of users who need to be able to launch Kubernetes clusters on GKE and GCE.
* A third group needs to have access to all of the available provider credentials on your account.

To set this up, create three teams:

* AWS Developers
* GKE/GCE Developers
* All Access

Next, create a workspace for each provider (Amazon, GKE, GCE, and Azure). Assign the appropriate teams to the workspaces:

* AWS Developers: Assign to the Amazon workspace.
* GKE/GCE Developers: Assign to the GKE and GCE workspaces.
* All Access: Assign to all four workspaces.

For instructions on creating a workspace, link:add-a-workspace.html[see our article on this topic].

**Related Articles**

* link:add-a-team.html[Add a Team]
* link:add-a-member.html[Add a Member]
* link:add-a-workspace.html[Add a Workspace]
